# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kang/gameEngineering/monster_mash/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kang/gameEngineering/monster_mash

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kang/gameEngineering/monster_mash/CMakeFiles /home/kang/gameEngineering/monster_mash/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kang/gameEngineering/monster_mash/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named monstermash

# Build rule for target.
monstermash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 monstermash
.PHONY : monstermash

# fast build rule for target.
monstermash/fast:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/build
.PHONY : monstermash/fast

cpanim.o: cpanim.cpp.o

.PHONY : cpanim.o

# target to build an object file
cpanim.cpp.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/cpanim.cpp.o
.PHONY : cpanim.cpp.o

cpanim.i: cpanim.cpp.i

.PHONY : cpanim.i

# target to preprocess a source file
cpanim.cpp.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/cpanim.cpp.i
.PHONY : cpanim.cpp.i

cpanim.s: cpanim.cpp.s

.PHONY : cpanim.s

# target to generate assembly for a file
cpanim.cpp.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/cpanim.cpp.s
.PHONY : cpanim.cpp.s

def3dsdl.o: def3dsdl.cpp.o

.PHONY : def3dsdl.o

# target to build an object file
def3dsdl.cpp.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/def3dsdl.cpp.o
.PHONY : def3dsdl.cpp.o

def3dsdl.i: def3dsdl.cpp.i

.PHONY : def3dsdl.i

# target to preprocess a source file
def3dsdl.cpp.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/def3dsdl.cpp.i
.PHONY : def3dsdl.cpp.i

def3dsdl.s: def3dsdl.cpp.s

.PHONY : def3dsdl.s

# target to generate assembly for a file
def3dsdl.cpp.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/def3dsdl.cpp.s
.PHONY : def3dsdl.cpp.s

defengarapl.o: defengarapl.cpp.o

.PHONY : defengarapl.o

# target to build an object file
defengarapl.cpp.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/defengarapl.cpp.o
.PHONY : defengarapl.cpp.o

defengarapl.i: defengarapl.cpp.i

.PHONY : defengarapl.i

# target to preprocess a source file
defengarapl.cpp.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/defengarapl.cpp.i
.PHONY : defengarapl.cpp.i

defengarapl.s: defengarapl.cpp.s

.PHONY : defengarapl.s

# target to generate assembly for a file
defengarapl.cpp.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/defengarapl.cpp.s
.PHONY : defengarapl.cpp.s

exportgltf.o: exportgltf.cpp.o

.PHONY : exportgltf.o

# target to build an object file
exportgltf.cpp.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/exportgltf.cpp.o
.PHONY : exportgltf.cpp.o

exportgltf.i: exportgltf.cpp.i

.PHONY : exportgltf.i

# target to preprocess a source file
exportgltf.cpp.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/exportgltf.cpp.i
.PHONY : exportgltf.cpp.i

exportgltf.s: exportgltf.cpp.s

.PHONY : exportgltf.s

# target to generate assembly for a file
exportgltf.cpp.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/exportgltf.cpp.s
.PHONY : exportgltf.cpp.s

loadsave.o: loadsave.cpp.o

.PHONY : loadsave.o

# target to build an object file
loadsave.cpp.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/loadsave.cpp.o
.PHONY : loadsave.cpp.o

loadsave.i: loadsave.cpp.i

.PHONY : loadsave.i

# target to preprocess a source file
loadsave.cpp.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/loadsave.cpp.i
.PHONY : loadsave.cpp.i

loadsave.s: loadsave.cpp.s

.PHONY : loadsave.s

# target to generate assembly for a file
loadsave.cpp.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/loadsave.cpp.s
.PHONY : loadsave.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o

.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i

.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s

.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

mypainter.o: mypainter.cpp.o

.PHONY : mypainter.o

# target to build an object file
mypainter.cpp.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/mypainter.cpp.o
.PHONY : mypainter.cpp.o

mypainter.i: mypainter.cpp.i

.PHONY : mypainter.i

# target to preprocess a source file
mypainter.cpp.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/mypainter.cpp.i
.PHONY : mypainter.cpp.i

mypainter.s: mypainter.cpp.s

.PHONY : mypainter.s

# target to generate assembly for a file
mypainter.cpp.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/mypainter.cpp.s
.PHONY : mypainter.cpp.s

mywindow.o: mywindow.cpp.o

.PHONY : mywindow.o

# target to build an object file
mywindow.cpp.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/mywindow.cpp.o
.PHONY : mywindow.cpp.o

mywindow.i: mywindow.cpp.i

.PHONY : mywindow.i

# target to preprocess a source file
mywindow.cpp.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/mywindow.cpp.i
.PHONY : mywindow.cpp.i

mywindow.s: mywindow.cpp.s

.PHONY : mywindow.s

# target to generate assembly for a file
mywindow.cpp.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/mywindow.cpp.s
.PHONY : mywindow.cpp.s

reconstruction.o: reconstruction.cpp.o

.PHONY : reconstruction.o

# target to build an object file
reconstruction.cpp.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/reconstruction.cpp.o
.PHONY : reconstruction.cpp.o

reconstruction.i: reconstruction.cpp.i

.PHONY : reconstruction.i

# target to preprocess a source file
reconstruction.cpp.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/reconstruction.cpp.i
.PHONY : reconstruction.cpp.i

reconstruction.s: reconstruction.cpp.s

.PHONY : reconstruction.s

# target to generate assembly for a file
reconstruction.cpp.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/reconstruction.cpp.s
.PHONY : reconstruction.cpp.s

third_party/SDL2_gfx-mod/SDL2_gfxPrimitives-mod.o: third_party/SDL2_gfx-mod/SDL2_gfxPrimitives-mod.c.o

.PHONY : third_party/SDL2_gfx-mod/SDL2_gfxPrimitives-mod.o

# target to build an object file
third_party/SDL2_gfx-mod/SDL2_gfxPrimitives-mod.c.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/SDL2_gfx-mod/SDL2_gfxPrimitives-mod.c.o
.PHONY : third_party/SDL2_gfx-mod/SDL2_gfxPrimitives-mod.c.o

third_party/SDL2_gfx-mod/SDL2_gfxPrimitives-mod.i: third_party/SDL2_gfx-mod/SDL2_gfxPrimitives-mod.c.i

.PHONY : third_party/SDL2_gfx-mod/SDL2_gfxPrimitives-mod.i

# target to preprocess a source file
third_party/SDL2_gfx-mod/SDL2_gfxPrimitives-mod.c.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/SDL2_gfx-mod/SDL2_gfxPrimitives-mod.c.i
.PHONY : third_party/SDL2_gfx-mod/SDL2_gfxPrimitives-mod.c.i

third_party/SDL2_gfx-mod/SDL2_gfxPrimitives-mod.s: third_party/SDL2_gfx-mod/SDL2_gfxPrimitives-mod.c.s

.PHONY : third_party/SDL2_gfx-mod/SDL2_gfxPrimitives-mod.s

# target to generate assembly for a file
third_party/SDL2_gfx-mod/SDL2_gfxPrimitives-mod.c.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/SDL2_gfx-mod/SDL2_gfxPrimitives-mod.c.s
.PHONY : third_party/SDL2_gfx-mod/SDL2_gfxPrimitives-mod.c.s

third_party/SDL2_gfx/SDL2_rotozoom.o: third_party/SDL2_gfx/SDL2_rotozoom.c.o

.PHONY : third_party/SDL2_gfx/SDL2_rotozoom.o

# target to build an object file
third_party/SDL2_gfx/SDL2_rotozoom.c.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/SDL2_gfx/SDL2_rotozoom.c.o
.PHONY : third_party/SDL2_gfx/SDL2_rotozoom.c.o

third_party/SDL2_gfx/SDL2_rotozoom.i: third_party/SDL2_gfx/SDL2_rotozoom.c.i

.PHONY : third_party/SDL2_gfx/SDL2_rotozoom.i

# target to preprocess a source file
third_party/SDL2_gfx/SDL2_rotozoom.c.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/SDL2_gfx/SDL2_rotozoom.c.i
.PHONY : third_party/SDL2_gfx/SDL2_rotozoom.c.i

third_party/SDL2_gfx/SDL2_rotozoom.s: third_party/SDL2_gfx/SDL2_rotozoom.c.s

.PHONY : third_party/SDL2_gfx/SDL2_rotozoom.s

# target to generate assembly for a file
third_party/SDL2_gfx/SDL2_rotozoom.c.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/SDL2_gfx/SDL2_rotozoom.c.s
.PHONY : third_party/SDL2_gfx/SDL2_rotozoom.c.s

third_party/image/imageReadWrite.o: third_party/image/imageReadWrite.cpp.o

.PHONY : third_party/image/imageReadWrite.o

# target to build an object file
third_party/image/imageReadWrite.cpp.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/image/imageReadWrite.cpp.o
.PHONY : third_party/image/imageReadWrite.cpp.o

third_party/image/imageReadWrite.i: third_party/image/imageReadWrite.cpp.i

.PHONY : third_party/image/imageReadWrite.i

# target to preprocess a source file
third_party/image/imageReadWrite.cpp.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/image/imageReadWrite.cpp.i
.PHONY : third_party/image/imageReadWrite.cpp.i

third_party/image/imageReadWrite.s: third_party/image/imageReadWrite.cpp.s

.PHONY : third_party/image/imageReadWrite.s

# target to generate assembly for a file
third_party/image/imageReadWrite.cpp.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/image/imageReadWrite.cpp.s
.PHONY : third_party/image/imageReadWrite.cpp.s

third_party/image/imageScale.o: third_party/image/imageScale.cpp.o

.PHONY : third_party/image/imageScale.o

# target to build an object file
third_party/image/imageScale.cpp.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/image/imageScale.cpp.o
.PHONY : third_party/image/imageScale.cpp.o

third_party/image/imageScale.i: third_party/image/imageScale.cpp.i

.PHONY : third_party/image/imageScale.i

# target to preprocess a source file
third_party/image/imageScale.cpp.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/image/imageScale.cpp.i
.PHONY : third_party/image/imageScale.cpp.i

third_party/image/imageScale.s: third_party/image/imageScale.cpp.s

.PHONY : third_party/image/imageScale.s

# target to generate assembly for a file
third_party/image/imageScale.cpp.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/image/imageScale.cpp.s
.PHONY : third_party/image/imageScale.cpp.s

third_party/image/imageUtils.o: third_party/image/imageUtils.cpp.o

.PHONY : third_party/image/imageUtils.o

# target to build an object file
third_party/image/imageUtils.cpp.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/image/imageUtils.cpp.o
.PHONY : third_party/image/imageUtils.cpp.o

third_party/image/imageUtils.i: third_party/image/imageUtils.cpp.i

.PHONY : third_party/image/imageUtils.i

# target to preprocess a source file
third_party/image/imageUtils.cpp.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/image/imageUtils.cpp.i
.PHONY : third_party/image/imageUtils.cpp.i

third_party/image/imageUtils.s: third_party/image/imageUtils.cpp.s

.PHONY : third_party/image/imageUtils.s

# target to generate assembly for a file
third_party/image/imageUtils.cpp.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/image/imageUtils.cpp.s
.PHONY : third_party/image/imageUtils.cpp.s

third_party/ir3d-utils/MeshBuilder.o: third_party/ir3d-utils/MeshBuilder.cpp.o

.PHONY : third_party/ir3d-utils/MeshBuilder.o

# target to build an object file
third_party/ir3d-utils/MeshBuilder.cpp.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/ir3d-utils/MeshBuilder.cpp.o
.PHONY : third_party/ir3d-utils/MeshBuilder.cpp.o

third_party/ir3d-utils/MeshBuilder.i: third_party/ir3d-utils/MeshBuilder.cpp.i

.PHONY : third_party/ir3d-utils/MeshBuilder.i

# target to preprocess a source file
third_party/ir3d-utils/MeshBuilder.cpp.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/ir3d-utils/MeshBuilder.cpp.i
.PHONY : third_party/ir3d-utils/MeshBuilder.cpp.i

third_party/ir3d-utils/MeshBuilder.s: third_party/ir3d-utils/MeshBuilder.cpp.s

.PHONY : third_party/ir3d-utils/MeshBuilder.s

# target to generate assembly for a file
third_party/ir3d-utils/MeshBuilder.cpp.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/ir3d-utils/MeshBuilder.cpp.s
.PHONY : third_party/ir3d-utils/MeshBuilder.cpp.s

third_party/ir3d-utils/regionToMesh.o: third_party/ir3d-utils/regionToMesh.cpp.o

.PHONY : third_party/ir3d-utils/regionToMesh.o

# target to build an object file
third_party/ir3d-utils/regionToMesh.cpp.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/ir3d-utils/regionToMesh.cpp.o
.PHONY : third_party/ir3d-utils/regionToMesh.cpp.o

third_party/ir3d-utils/regionToMesh.i: third_party/ir3d-utils/regionToMesh.cpp.i

.PHONY : third_party/ir3d-utils/regionToMesh.i

# target to preprocess a source file
third_party/ir3d-utils/regionToMesh.cpp.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/ir3d-utils/regionToMesh.cpp.i
.PHONY : third_party/ir3d-utils/regionToMesh.cpp.i

third_party/ir3d-utils/regionToMesh.s: third_party/ir3d-utils/regionToMesh.cpp.s

.PHONY : third_party/ir3d-utils/regionToMesh.s

# target to generate assembly for a file
third_party/ir3d-utils/regionToMesh.cpp.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/ir3d-utils/regionToMesh.cpp.s
.PHONY : third_party/ir3d-utils/regionToMesh.cpp.s

third_party/miscutils/camera.o: third_party/miscutils/camera.cpp.o

.PHONY : third_party/miscutils/camera.o

# target to build an object file
third_party/miscutils/camera.cpp.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/miscutils/camera.cpp.o
.PHONY : third_party/miscutils/camera.cpp.o

third_party/miscutils/camera.i: third_party/miscutils/camera.cpp.i

.PHONY : third_party/miscutils/camera.i

# target to preprocess a source file
third_party/miscutils/camera.cpp.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/miscutils/camera.cpp.i
.PHONY : third_party/miscutils/camera.cpp.i

third_party/miscutils/camera.s: third_party/miscutils/camera.cpp.s

.PHONY : third_party/miscutils/camera.s

# target to generate assembly for a file
third_party/miscutils/camera.cpp.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/miscutils/camera.cpp.s
.PHONY : third_party/miscutils/camera.cpp.s

third_party/miscutils/def3d.o: third_party/miscutils/def3d.cpp.o

.PHONY : third_party/miscutils/def3d.o

# target to build an object file
third_party/miscutils/def3d.cpp.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/miscutils/def3d.cpp.o
.PHONY : third_party/miscutils/def3d.cpp.o

third_party/miscutils/def3d.i: third_party/miscutils/def3d.cpp.i

.PHONY : third_party/miscutils/def3d.i

# target to preprocess a source file
third_party/miscutils/def3d.cpp.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/miscutils/def3d.cpp.i
.PHONY : third_party/miscutils/def3d.cpp.i

third_party/miscutils/def3d.s: third_party/miscutils/def3d.cpp.s

.PHONY : third_party/miscutils/def3d.s

# target to generate assembly for a file
third_party/miscutils/def3d.cpp.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/miscutils/def3d.cpp.s
.PHONY : third_party/miscutils/def3d.cpp.s

third_party/miscutils/fsutils.o: third_party/miscutils/fsutils.cpp.o

.PHONY : third_party/miscutils/fsutils.o

# target to build an object file
third_party/miscutils/fsutils.cpp.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/miscutils/fsutils.cpp.o
.PHONY : third_party/miscutils/fsutils.cpp.o

third_party/miscutils/fsutils.i: third_party/miscutils/fsutils.cpp.i

.PHONY : third_party/miscutils/fsutils.i

# target to preprocess a source file
third_party/miscutils/fsutils.cpp.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/miscutils/fsutils.cpp.i
.PHONY : third_party/miscutils/fsutils.cpp.i

third_party/miscutils/fsutils.s: third_party/miscutils/fsutils.cpp.s

.PHONY : third_party/miscutils/fsutils.s

# target to generate assembly for a file
third_party/miscutils/fsutils.cpp.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/miscutils/fsutils.cpp.s
.PHONY : third_party/miscutils/fsutils.cpp.s

third_party/miscutils/mesh3d.o: third_party/miscutils/mesh3d.cpp.o

.PHONY : third_party/miscutils/mesh3d.o

# target to build an object file
third_party/miscutils/mesh3d.cpp.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/miscutils/mesh3d.cpp.o
.PHONY : third_party/miscutils/mesh3d.cpp.o

third_party/miscutils/mesh3d.i: third_party/miscutils/mesh3d.cpp.i

.PHONY : third_party/miscutils/mesh3d.i

# target to preprocess a source file
third_party/miscutils/mesh3d.cpp.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/miscutils/mesh3d.cpp.i
.PHONY : third_party/miscutils/mesh3d.cpp.i

third_party/miscutils/mesh3d.s: third_party/miscutils/mesh3d.cpp.s

.PHONY : third_party/miscutils/mesh3d.s

# target to generate assembly for a file
third_party/miscutils/mesh3d.cpp.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/miscutils/mesh3d.cpp.s
.PHONY : third_party/miscutils/mesh3d.cpp.s

third_party/miscutils/opengltools.o: third_party/miscutils/opengltools.cpp.o

.PHONY : third_party/miscutils/opengltools.o

# target to build an object file
third_party/miscutils/opengltools.cpp.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/miscutils/opengltools.cpp.o
.PHONY : third_party/miscutils/opengltools.cpp.o

third_party/miscutils/opengltools.i: third_party/miscutils/opengltools.cpp.i

.PHONY : third_party/miscutils/opengltools.i

# target to preprocess a source file
third_party/miscutils/opengltools.cpp.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/miscutils/opengltools.cpp.i
.PHONY : third_party/miscutils/opengltools.cpp.i

third_party/miscutils/opengltools.s: third_party/miscutils/opengltools.cpp.s

.PHONY : third_party/miscutils/opengltools.s

# target to generate assembly for a file
third_party/miscutils/opengltools.cpp.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/miscutils/opengltools.cpp.s
.PHONY : third_party/miscutils/opengltools.cpp.s

third_party/tinygltf/tinygltf.o: third_party/tinygltf/tinygltf.cpp.o

.PHONY : third_party/tinygltf/tinygltf.o

# target to build an object file
third_party/tinygltf/tinygltf.cpp.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/tinygltf/tinygltf.cpp.o
.PHONY : third_party/tinygltf/tinygltf.cpp.o

third_party/tinygltf/tinygltf.i: third_party/tinygltf/tinygltf.cpp.i

.PHONY : third_party/tinygltf/tinygltf.i

# target to preprocess a source file
third_party/tinygltf/tinygltf.cpp.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/tinygltf/tinygltf.cpp.i
.PHONY : third_party/tinygltf/tinygltf.cpp.i

third_party/tinygltf/tinygltf.s: third_party/tinygltf/tinygltf.cpp.s

.PHONY : third_party/tinygltf/tinygltf.s

# target to generate assembly for a file
third_party/tinygltf/tinygltf.cpp.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/tinygltf/tinygltf.cpp.s
.PHONY : third_party/tinygltf/tinygltf.cpp.s

third_party/triangle/triangle.o: third_party/triangle/triangle.c.o

.PHONY : third_party/triangle/triangle.o

# target to build an object file
third_party/triangle/triangle.c.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/triangle/triangle.c.o
.PHONY : third_party/triangle/triangle.c.o

third_party/triangle/triangle.i: third_party/triangle/triangle.c.i

.PHONY : third_party/triangle/triangle.i

# target to preprocess a source file
third_party/triangle/triangle.c.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/triangle/triangle.c.i
.PHONY : third_party/triangle/triangle.c.i

third_party/triangle/triangle.s: third_party/triangle/triangle.c.s

.PHONY : third_party/triangle/triangle.s

# target to generate assembly for a file
third_party/triangle/triangle.c.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/triangle/triangle.c.s
.PHONY : third_party/triangle/triangle.c.s

third_party/zip-mod/zip.o: third_party/zip-mod/zip.c.o

.PHONY : third_party/zip-mod/zip.o

# target to build an object file
third_party/zip-mod/zip.c.o:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/zip-mod/zip.c.o
.PHONY : third_party/zip-mod/zip.c.o

third_party/zip-mod/zip.i: third_party/zip-mod/zip.c.i

.PHONY : third_party/zip-mod/zip.i

# target to preprocess a source file
third_party/zip-mod/zip.c.i:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/zip-mod/zip.c.i
.PHONY : third_party/zip-mod/zip.c.i

third_party/zip-mod/zip.s: third_party/zip-mod/zip.c.s

.PHONY : third_party/zip-mod/zip.s

# target to generate assembly for a file
third_party/zip-mod/zip.c.s:
	$(MAKE) -f CMakeFiles/monstermash.dir/build.make CMakeFiles/monstermash.dir/third_party/zip-mod/zip.c.s
.PHONY : third_party/zip-mod/zip.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... monstermash"
	@echo "... cpanim.o"
	@echo "... cpanim.i"
	@echo "... cpanim.s"
	@echo "... def3dsdl.o"
	@echo "... def3dsdl.i"
	@echo "... def3dsdl.s"
	@echo "... defengarapl.o"
	@echo "... defengarapl.i"
	@echo "... defengarapl.s"
	@echo "... exportgltf.o"
	@echo "... exportgltf.i"
	@echo "... exportgltf.s"
	@echo "... loadsave.o"
	@echo "... loadsave.i"
	@echo "... loadsave.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... mypainter.o"
	@echo "... mypainter.i"
	@echo "... mypainter.s"
	@echo "... mywindow.o"
	@echo "... mywindow.i"
	@echo "... mywindow.s"
	@echo "... reconstruction.o"
	@echo "... reconstruction.i"
	@echo "... reconstruction.s"
	@echo "... third_party/SDL2_gfx-mod/SDL2_gfxPrimitives-mod.o"
	@echo "... third_party/SDL2_gfx-mod/SDL2_gfxPrimitives-mod.i"
	@echo "... third_party/SDL2_gfx-mod/SDL2_gfxPrimitives-mod.s"
	@echo "... third_party/SDL2_gfx/SDL2_rotozoom.o"
	@echo "... third_party/SDL2_gfx/SDL2_rotozoom.i"
	@echo "... third_party/SDL2_gfx/SDL2_rotozoom.s"
	@echo "... third_party/image/imageReadWrite.o"
	@echo "... third_party/image/imageReadWrite.i"
	@echo "... third_party/image/imageReadWrite.s"
	@echo "... third_party/image/imageScale.o"
	@echo "... third_party/image/imageScale.i"
	@echo "... third_party/image/imageScale.s"
	@echo "... third_party/image/imageUtils.o"
	@echo "... third_party/image/imageUtils.i"
	@echo "... third_party/image/imageUtils.s"
	@echo "... third_party/ir3d-utils/MeshBuilder.o"
	@echo "... third_party/ir3d-utils/MeshBuilder.i"
	@echo "... third_party/ir3d-utils/MeshBuilder.s"
	@echo "... third_party/ir3d-utils/regionToMesh.o"
	@echo "... third_party/ir3d-utils/regionToMesh.i"
	@echo "... third_party/ir3d-utils/regionToMesh.s"
	@echo "... third_party/miscutils/camera.o"
	@echo "... third_party/miscutils/camera.i"
	@echo "... third_party/miscutils/camera.s"
	@echo "... third_party/miscutils/def3d.o"
	@echo "... third_party/miscutils/def3d.i"
	@echo "... third_party/miscutils/def3d.s"
	@echo "... third_party/miscutils/fsutils.o"
	@echo "... third_party/miscutils/fsutils.i"
	@echo "... third_party/miscutils/fsutils.s"
	@echo "... third_party/miscutils/mesh3d.o"
	@echo "... third_party/miscutils/mesh3d.i"
	@echo "... third_party/miscutils/mesh3d.s"
	@echo "... third_party/miscutils/opengltools.o"
	@echo "... third_party/miscutils/opengltools.i"
	@echo "... third_party/miscutils/opengltools.s"
	@echo "... third_party/tinygltf/tinygltf.o"
	@echo "... third_party/tinygltf/tinygltf.i"
	@echo "... third_party/tinygltf/tinygltf.s"
	@echo "... third_party/triangle/triangle.o"
	@echo "... third_party/triangle/triangle.i"
	@echo "... third_party/triangle/triangle.s"
	@echo "... third_party/zip-mod/zip.o"
	@echo "... third_party/zip-mod/zip.i"
	@echo "... third_party/zip-mod/zip.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

